### ISSUE TITLE
Issue with Mako 4.5.8 - undefined method register()

### ISSUE THREAD

**Issue by marcomontalbano** [mako-framework/toolbar#1]
Hi,
I'm working with Mako Framework 4.5.8 and I tried to include the toolbar, but it throws me the following error:
`Fatal error: Call to undefined method mako\toolbar\ToolbarPackage::register() in .../vendor/mako/framework/src/mako/application/Application.php on line 322`

I tried to change the method name from boot() to register() and it works fine.

Could it be the solution?

thanks

**Comment by freost** [comment]
Hi,

I think the problem is that you added the package to the list of [services](https://github.com/mako-framework/app/blob/master/app/config/application.php#L141) instead of the list of [packages](https://github.com/mako-framework/app/blob/master/app/config/application.php#L190).

**Comment by marcomontalbano** [comment]
My fault,

thank you very much!
