### ISSUE TITLE
Inline Javascript en CSS is blocked by Content Security Policy

### ISSUE THREAD

**Issue by mathysie** [mako-framework/toolbar#2]
I'd like to use the mako toolbar for my project. However, my browser's console outputs
> Content Security Policy: The page’s settings blocked the loading of a resource at self

Is it possible to support Content Security Policy by relocating the code in `<script>` and `<style>` blocks to separate files?

**Comment by freost** [comment]
I guess I could add an "assets" route that serves the js and css. We usually just disable CSP headers in our dev environment.

**Comment by mathysie** [comment]
I would prefer adding an 'assets' route. Our development is a collaboration including very inexperienced developer, so we would like to keep the CSP headers in development to avoid bugs only existing in production.

**Comment by freost** [comment]
Sorry for taking so long. Had a look at this today and noticed an issue; Symfony's var-dumper component injects inline JavaScript so it won't help if we move our assets to "asset routes".

**Comment by mathysie** [comment]
Thanks for looking into it! In that case disabling CSP headers would be better.
